version: "3.7"
services:
    app:
        build:
            args:
                user: 'chernyatinai'
                uid: 1004
            context: ..
            dockerfile: ./docker/Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travellist

    db:
        image: mysql:5.7
        container_name: travellist-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'laraapp_db'
            MYSQL_ROOT_PASSWORD:
            #            MYSQL_PASSWORD: ${DB_PASSWORD}
            #            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ../docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - travellist

    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ../docker/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

    redis:
        image: redis:alpine
        container_name: app_redis
        volumes:
            - ../docker/redis:/usr/local/etc/redis/redis.conf
        ports:
            - 6379:6379
        networks:
            - travellist
networks:
    travellist:
        driver: bridge
