version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        image: loyalty-backend
        container_name: loyalty-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    nginx:
        image: nginx:alpine
        container_name: loyalty-nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/

    redis:
        image: redis:alpine
        container_name: loyalty-redis
        volumes:
            - ./docker/redis:/usr/local/etc/redis/redis.conf
        ports:
            - 6378:6378

networks:
    loyalty:
        driver: bridge
